### ISSUE TITLE
Token 0

### ISSUE THREAD

**Issue by vespuccieth** [hashlips-lab/safe-nft-metadata-provider#29]
Hey, I'm still having a problem with token 0. Can you please tell me how I can change settings so that script starts with 0 instead of 1?

**Comment by liarco** [comment]
Hi @vespuccieth, unfortunately this system has an hard-coded initial token ID of `1` so I can't provide you with quick solution for this. I don't want to give you instructions that may produce unwanted side-effects.

Is your collection already deployed? Would you mind explaining why you need an initial token ID of `0` instead of `1`? This is pretty uncommon.

**Comment by vespuccieth** [comment]
> Hi @vespuccieth, unfortunately this system has an hard-coded initial token ID of `1` so I can't provide you with quick solution for this. I don't want to give you instructions that may produce unwanted side-effects.
> 
> Is your collection already deployed? Would you mind explaining why you need an initial token ID of `0` instead of `1`? This is pretty uncommon.

I'm using erc-721A so it's very common. You can try to read function tokenURI id 0 and you'll see that the token exists / collection starts with 0.

https://etherscan.io/address/0x7581f90f03f1f3ed8dc1755caecb4fd2495c48c6#readContract
https://etherscan.io/address/0x16ef6e8563456283f50654a8fb16056a88eecbb5#readContract
https://etherscan.io/address/0xed5af388653567af2f388e6224dc7c4b3241c544#readContract

Is there a way to manually (via script console) generate / publish that token?

**Comment by liarco** [comment]
Ok, I know that contract. If so, then you should probably upgrade your `ERC721A` version to `3.0.0` because they introduced the possibility to choose an arbitrary starting token ID. You can also use [our all-in-one solution](https://github.com/hashlips-lab/nft-erc721-collection) in order to create your contract. The next version (which we are about to release very soon) will be using the `ERC721A` contract.

You can find videos about this on [my YouTube channel](https://www.youtube.com/channel/UCsNUSP49XDIhxaZoZlLwnyw) as well as on the [HashLips](https://www.youtube.com/c/HashLipsNFT)' one.

**Comment by vespuccieth** [comment]
Sounds great, thank you!
