### ISSUE TITLE
Not compatible with ERC721A 

### ISSUE THREAD

**Issue by R-qanawati** [hashlips-lab/safe-nft-metadata-provider#30]
I have tested this and it works well with ERC721 and tokens starting at 1 but if it is ERC721A and token ids start at 0 it doesn't read the supply for some reason. Always returns hidden for 0 and the rest are errors.

**Comment by liarco** [comment]
Hi @R-qanawati,
I'm sorry but the title is a bit misleading. `ERC721A` supports arbitrary start token ID since version `3.0.0` so it's compatible with this tool as long as you set the start ID to `1` instead of `0`.
We have an [all-in-one solution for collections](https://github.com/hashlips-lab/nft-erc721-collection) that is based on `ERC721A` since version `2.0.0` and starts with token ID 1 while keeping all the benefit of the Azuki implementation.

Feel free to let me know if you need further information or you can also check out [my YouTube channel](https://www.youtube.com/channel/UCsNUSP49XDIhxaZoZlLwnyw) for demos and tutorials. 😉

**Comment by R-qanawati** [comment]
i understand but if you deployed already and its set to starting token id 0 it is no longer working correct? there is no way to fix it unless you change the erc721a implementation

**Comment by liarco** [comment]
@R-qanawati that's correct, the current implementation of this tool doesn't support an arbitrary start token ID. However you should be able to make it work by changing the application code. Unfortunately I don't have any example at the moment.
