### ISSUE TITLE
Digital Ocean Metadata

### ISSUE THREAD

**Issue by VeriumETH** [hashlips-lab/safe-nft-metadata-provider#37]
Hello @liarco 

My digital ocean metadata is showing up on a single line. 

`{"name":"NFT Name #1","image":"http:\/\/test-9zf53.ondigitalocean.app\/asset\/1.png","attributes":[{"trait_type":"Background","value":"Off White C"},{"trait_type":"Race","value":"Red"},{"trait_type":"Eyes","value":"Joyful"},{"trait_type":"Clothing","value":"Bumblebee Jacket"},{"trait_type":"Mouth","value":"Pout"},{"trait_type":"Hair","value":"Green Samurai"}]}`

Why does it appear this way? Thank you for your help in advance. The ERC721A integration is beautiful on mainnet and gas fees are insanely low. The dapp functions on both mobile metamask app and desktop chrome flawlessly. Bless you, sir!

**Comment by liarco** [comment]
Hi @VeriumETH,
that's correct! JSON format can be minified like that and it works perfectly fine. The reason why you see it "beautified" in our videos is because we are using a JSON parser extension for Chrome: https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh

Also thank you for your feedback, I really appreciate it.
