### ISSUE TITLE
Error when deploying to Digital Ocean

### ISSUE THREAD

**Issue by jvel07** [hashlips-lab/safe-nft-metadata-provider#58]
After hitting "Deploy to Digital Ocean" the website shows "error when trying to create the app" and gives the option to start over.
Start-over takes you to a wizard with the basic information of the app; the app deploys successfully but all the env variables are lost... I'd assume it's just a matter of versioning?

**Comment by liarco** [comment]
Hi @jvel07, thanks for reporting this issue. I'm able to reproduce the error, but in my case the ENV vars are still there when I click the "Start Over" button.

I'm gonna reach out to DigitalOcean since it looks like it might be an issue on their end.

**Comment by liarco** [comment]
@jvel07 as far as I know CloudFlare supports 2 types of deployments:
- **static websites:** same as the minting dapp from my other tool, this is a simple set of static files to be served from a CDN, no back end code
- **serverless functions:** this is a way to create a back end made of single functions that get spawned and run whenever the endpoint is called. This means that you pay based on the resource you use on each call and you have no server running 24/7

Unfortunately none of these deployment options work with this app, since we have to keep listening for new mint events. Anyway I got in touch with DigitalOcean and they told me they are investigating on the issue.

**Comment by jvel07** [comment]
@liarco, thanks for the reply.
Is this solution only for collections that have instant reveals? If the reveal happens, say, 24 hours after mint this app wouldn't be needed, would it be?

**Comment by liarco** [comment]
@jvel07 this tools is pretty much the only option whenever you need to reveal your collection before it's sold out. It doesn't matter how much time it takes before you reveal, what matters is the actual amount of token left to be minted at reveal time.

Without a tool like this, then any tokens that weren't minted before reveal will be freely accessible to snipers.

**Comment by jvel07** [comment]
Yes, totally agree with you on that.

What I actually tried to say is about the reveal happening after the collection is minted out.

Supposing all the items were minted, then the next step is to reveal them (after sold out); in this case, it wouldn't be necessary, right?

**Comment by jvel07** [comment]
Yes, @liarco. I totally agree with you on that. :)

What I actually tried to say is about the reveal happening after the collection is minted out.

Supposing all the items were minted, then the next step is to reveal them (after sold out); in this case, it wouldn't be necessary, right?

**Comment by liarco** [comment]
@jvel07 yes, that's correct! A little thing to add here: I would also suggest not to upload the assets and metadata on IPFS before mint out. The reason for this applies especially with highly hyped collections, because IPFS data is public and it's possible to watch for new data added to the network and download it before it gets revealed on-chain.

Anyway, this doesn't make any difference on the main topic: if your plan is to reveal after mint out, then you can avoid using this tool.

**Comment by liarco** [comment]
I just got an update from DigitalOcean and they finally fixed the button. I wanna thank everyone who reported the issue and I'm sorry for the inconvenience.

**Comment by bidneso** [comment]
> I just got an update from DigitalOcean and they finally fixed the button. I wanna thank everyone who reported the issue and I'm sorry for the inconvenience.

Hey, I have just tried deploying to DigitalOcean and am receiving the same errors again. 

"checking autoscaling flipper: getting owner: getting team data: rpc error: code = NotFound desc = team not found"
